### PR TITLE
Remove oic.wk.d from oic.d.virtual

### PR DESCRIPTION
**Pull request by SiMet**
All devices shall contain oic.wk.d resource. Device map shall only list resources which are Vertical.

### CODE REVIEW

**Comment by marktrayer** [comment]
Please see latest version of this file on the BZ 2011 branch.

**Comment by SiMet** [comment]
@marktrayer do you mean Bugzilla-2114?
I see that there is no element 'resources'. In my opinion it shall exist and be an empty array

**Comment by marktrayer** [comment]
The schema that governs the content map intentionally didn't make the Resource array required.  I'll enforce that if this makes the machine reading of the content easier (i.e. you expect to always get an array then inspect contents vs. having to check for the existence of the array).  Please let me know.

**Comment by SiMet** [comment]
@marktrayer currently I expect that there will be an array.
However, it's easy change so it doesn't matter for me.

**Comment by marktrayer** [comment]
PR was covered by separate equivalent pull requests that were merged in April.  Please raise a new PR if there are further issues to be resolved.

**Pull request closed without merging**
